# https://pyo3.rs/v0.23.3/python-typing-hints.html#my_projectpyi-content
from enum import Enum

class Diacritic(Enum): ...

def syllabify_el(s: str) -> list[str]: ...
def syllabify_el_mode(s: str, merge: bool) -> list[str]: ...
def syllabify_el_mode_at(s: str, idxs: list[int]) -> list[str]: ...

# Temporary: to delete eventually (?)
def syllabify_gr(s: str) -> list[str]: ...
def syllabify_gr_ref(s: str) -> list[str]: ...

# Accent utilities
def remove_all_diacritics(s: str) -> str: ...
def remove_diacritic_at(s: str, pos: int, diacritic: str) -> str: ...
def add_acute_at(s: str, pos: int) -> str:
    """Add acute to the one-indexed syllable from the end."""

def has_diacritic(s: str, diacritic: str) -> bool: ...
def to_monotonic(s: str) -> str: ...
