# https://pyo3.rs/v0.23.3/python-typing-hints.html#my_projectpyi-content
from enum import Enum

class Diacritic(Enum): ...

# Syllabification
def syllabify(s: str) -> list[str]: ...
def syllabify_with_merge(s: str, merge: bool) -> list[str]: ...
def syllabify_with_merge_at(s: str, idxs: list[int]) -> list[str]: ...

# Accent utilities
def remove_all_diacritics(s: str) -> str: ...
def remove_diacritic_at(s: str, pos: int, diacritic: str) -> str: ...
def add_acute_at(s: str, pos: int) -> str: ...
def has_diacritic(s: str, diacritic: str) -> bool: ...

# Monotonic
def to_monotonic(s: str) -> str: ...
