[package]
name = "py-grac"
version = "0.1.2"
edition = "2024"

[lib]
name = "grac"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.23.0", features = ["extension-module"] }
grac = { path = "../" }
