[package]
name = "py-grac"
version = "0.1.0"
edition = "2021"

[lib]
name = "grac"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.23.0", features = ["extension-module"] }
grac = { version = "0.1.0", path = "../" }
